version: '3'

services:
  app:
    container_name: poissons
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn --host 0.0.0.0 --port 9001 quiz_poissons.asgi:application
    image: cangt/poissons:0.1.0
    env_file:
      - .env
    hostname: ${HOST}
    domainname: ${HOST}
    volumes:
      - ./upload:/app/upload
      - ./static:/app/static
    network_mode: host
    # extra_hosts:
    #       -  "host.docker.internal:host-gateway"

volumes:
  upload:
  static:

